package it.akademija.journal;

/**
 * SUCCESSFUL_LOGIN - sėkmingas prisijungimas UNSUCCESSFUL_LOGIN - nesėkmingas
 * prisijungimas LOGOUT - atsijungimas APPLICATION_SUBMITED - pateiktas naujas
 * prašymas APPLICATION_DELETED - ištrintas prašymas MEDICAL_RECORD_SUBMITED -
 * medicininė pažyma įkelta MEDICAL_RECORD_DOWNLOADED - medicininė pažyma
 * atsisiųsta USER_CREATED - naujas naudotojas sukurtas USER_DATA_CHANGED -
 * naudotojo anketos duomenys pakeisti USER_DELETED - naudotojas ištrintas
 * KINDERGARTEN_CREATED - sukurtas naujas darželis KINDERGARTEN_UPDATED -
 * atnaujinti darželio duomenys (čia būtų gerai pridėti į entryMessage, kas buvo
 * konkrečiai padaryta: pakeistas vietų skaičius iki x, pakeistas pavadinimas,
 * pakeistas adresas - tai, ką galima padaryti su darželiu KINDERGARTEN_DELETED
 * - ištrintas darželis REGISTRATION_STARTED - prašymų registracija pradėta
 * REGISTRATION_ENDED - prašymų registracija baigta
 *
 */

public enum OperationType {

	SUCCESSFUL_LOGIN, UNSUCCESSFUL_LOGIN, LOGOUT, APPLICATION_SUBMITED, APPLICATION_DELETED, APPLICATION_DELETE_FAILED, APPLICATION_DEACTIVATED, APPLICATION_DEACTIVATE_FAILED,
	APPLICATION_SUBMIT_FAILED, MEDICAL_RECORD_SUBMITED, MEDICAL_RECORD_SUBMIT_FAILED, MEDICAL_RECORD_DELETE,
	MEDICAL_RECORD_DOWNLOADED, USER_CREATED, USER_CREATE_FAILED,USER_DATA_CHANGED, USER_DATA_CHANGE_FAILED, USER_DELETED, USER_DELETE_FAILED, KINDERGARTEN_CREATED, KINDERGARTEN_CREATE_FAILED,
	KINDERGARTEN_UPDATED, KINDERGARTEN_UPDATE_FAILED, KINDERGARTEN_DELETED, REGISTRATION_STARTED, REGISTRATION_ENDED,
	QUEUE_FORM, QUEUE_CONFIRM, QUEUE_LOCK, QUEUE_UNLOCK, APPLICATION_DOWNLOAD, APPLICATION_DOWNLOAD_FAILED, COMPENSATION_DOWNLOAD, COMPENSATION_DOWNLOAD_FAILED,
	COMPENSATION_SUBMIT, COMPENSATION_SUBMIT_FAILED, COMPENSATION_DELETE, COMPENSATION_DELETE_FAILED, RESET_REQUEST_DELETE, RESET_REQUEST

}
